//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.foodProgramDate = new HashSet<foodProgramDate>();
            this.goals = new HashSet<goals>();
            this.measurementCM = new HashSet<measurementCM>();
            this.measureMM = new HashSet<measureMM>();
            this.progressImage = new HashSet<progressImage>();
            this.trainingProgramDate = new HashSet<trainingProgramDate>();
            this.trainingSale = new HashSet<trainingSale>();
        }
    
        public int CID { get; set; }
        public string ID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public short gender { get; set; }
        public string kennitala { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string foodPref { get; set; }
        public string injury { get; set; }
        public string allergy { get; set; }
        public Nullable<int> zipcodes_ZIP { get; set; }
        public string profileImagePath { get; set; }
        public int height { get; set; }
        public Nullable<int> trainer_TRID { get; set; }
        public Nullable<bool> hidden { get; set; }
        public short jobDifficulty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        public virtual trainer trainer { get; set; }
        public virtual zipcodes zipcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foodProgramDate> foodProgramDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goals> goals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<measurementCM> measurementCM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<measureMM> measureMM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<progressImage> progressImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trainingProgramDate> trainingProgramDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trainingSale> trainingSale { get; set; }
    }
}
