//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public foodItem()
        {
            this.foodPortion = new HashSet<foodPortion>();
        }
    
        public int FIID { get; set; }
        public string name { get; set; }
        public decimal kcal { get; set; }
        public decimal fat { get; set; }
        public decimal saturatedFat { get; set; }
        public decimal unsaturatedFat { get; set; }
        public decimal colestrol { get; set; }
        public decimal carbohydrate { get; set; }
        public decimal addedSugar { get; set; }
        public decimal fiber { get; set; }
        public decimal water { get; set; }
        public decimal protein { get; set; }
        public Nullable<bool> suppliment { get; set; }
        public Nullable<int> trainer_TRID { get; set; }
        public string category { get; set; }
    
        public virtual trainer trainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foodPortion> foodPortion { get; set; }
    }
}
