//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public foodProgram()
        {
            this.foodProgramDate = new HashSet<foodProgramDate>();
        }
    
        public int FPMID { get; set; }
        public Nullable<int> foodPortion_FPID { get; set; }
        public Nullable<int> trainer_TRID { get; set; }
    
        public virtual foodPortion foodPortion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foodProgramDate> foodProgramDate { get; set; }
        public virtual trainer trainer { get; set; }
    }
}
