//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodProgramPortion
    {
        public int foodProgram_FPMID { get; set; }
        public int foodPortion_FPID { get; set; }
        public short weekday { get; set; }
        public short timeOfDay { get; set; }
    
        public virtual foodProgram foodProgram { get; set; }
        public virtual foodPortion foodPortion { get; set; }
    }
}
