//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class goals
    {
        public int GID { get; set; }
        public Nullable<int> customer_CID { get; set; }
        public Nullable<decimal> kg { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public string description { get; set; }
        public Nullable<decimal> diameter { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime dueDate { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
