//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class measureMM
    {
        public int MMMID { get; set; }
        public Nullable<int> customer_CID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> chest { get; set; }
        public Nullable<decimal> abdominal { get; set; }
        public Nullable<decimal> thigh { get; set; }
        public Nullable<decimal> tricep { get; set; }
        public Nullable<decimal> subscapular { get; set; }
        public Nullable<decimal> suprailiac { get; set; }
        public Nullable<decimal> axilliary { get; set; }
        public Nullable<decimal> bmi { get; set; }
        public Nullable<decimal> lbm { get; set; }
        public Nullable<decimal> fatPercentage { get; set; }
        public Nullable<decimal> kg { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
