//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingProgramDate
    {
        public int TDID { get; set; }
        public Nullable<int> customer_CID { get; set; }
        public Nullable<int> trainingProgram_TPID { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual trainingProgram trainingProgram { get; set; }
    }
}
