//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingSaleProduct
    {
        public int price { get; set; }
        public int duration { get; set; }
        public int trainingSale_TSID { get; set; }
        public int product_PID { get; set; }
        public System.DateTime endDate { get; set; }
    
        public virtual product product { get; set; }
        public virtual trainingSale trainingSale { get; set; }
    }
}
