//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public training()
        {
            this.trainingProgramTraining = new HashSet<trainingProgramTraining>();
        }
    
        public int TID { get; set; }
        public Nullable<int> numberOfSets { get; set; }
        public Nullable<int> numberOfReps { get; set; }
        public int exercise_EID { get; set; }
        public Nullable<int> durationMin { get; set; }
        public Nullable<int> restBetweenMin { get; set; }
        public bool sunday { get; set; }
        public bool monday { get; set; }
        public bool tuesday { get; set; }
        public bool wednesday { get; set; }
        public bool thursday { get; set; }
        public bool friday { get; set; }
        public bool saturday { get; set; }
        public string timeOfDay { get; set; }
        public string className { get; set; }
    
        public virtual exercise exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trainingProgramTraining> trainingProgramTraining { get; set; }
    }
}
