//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public training()
        {
            this.trainingProgram = new HashSet<trainingProgram>();
        }
    
        public int TID { get; set; }
        public Nullable<int> numberOfSets { get; set; }
        public Nullable<int> numberOfReps { get; set; }
        public Nullable<int> exercise_EID { get; set; }
        public Nullable<int> durationMin { get; set; }
        public Nullable<int> restBetweenMin { get; set; }
        public short weekday { get; set; }
        public Nullable<System.DateTime> timeOfday { get; set; }
    
        public virtual exercise exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trainingProgram> trainingProgram { get; set; }
    }
}
