//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingMasterWebAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingProgramTraining
    {
        public int trainingProgram_TPID { get; set; }
        public int training_TID { get; set; }
        public short weekday { get; set; }
        public short timeOfDay { get; set; }
    
        public virtual training training { get; set; }
        public virtual trainingProgram trainingProgram { get; set; }
    }
}
